import Foundation
import WidgetKit

enum SnapshotPublisher {
    /// Returns nil for normal GUI launch. These commands never initialize NSApplication.
    static func run(arguments: [String]) -> Int32? {
        guard let command = arguments.first, command.hasPrefix("--") else { return nil }
        do {
            switch command {
            case "--check-storage":
                guard arguments.count == 1 else { return usage() }
                let destination = try SnapshotStore.sharedURL()
                let directory = destination.deletingLastPathComponent()
                // Same private mode as `SnapshotStore.publish`; the installer runs this check first.
                try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true,
                                                        attributes: [.posixPermissions: 0o700])
                let probe = directory.appendingPathComponent(".bars-check-\(UUID().uuidString)")
                defer { try? FileManager.default.removeItem(at: probe) }
                try Data("Bars storage check".utf8).write(to: probe, options: .atomic)
                guard try Data(contentsOf: probe) == Data("Bars storage check".utf8) else {
                    throw SnapshotError.sharedContainerUnavailable
                }
                print(destination.path)
            case "--publish-snapshot":
                guard arguments.count == 2 || (arguments.count == 3 && arguments[2] == "--no-reload") else {
                    return usage()
                }
                let source = URL(fileURLWithPath: arguments[1])
                try SnapshotStore.publish(from: source, to: SnapshotStore.sharedURL())
                if arguments.count == 2 { requestReload() }
            case "--reload-widgets":
                // The installer uses this after replacing the bundle and ending the previous
                // extension process, so the timeline is regenerated by the new code.
                guard arguments.count == 1 else { return usage() }
                requestReload()
            default: return usage()
            }
            return 0
        } catch {
            // Do not echo paths or snapshot contents into scheduler logs.
            let explanation = (error as? SnapshotError)?.localizedDescription
                ?? "Could not access or publish the widget snapshot. Check installation and file permissions."
            FileHandle.standardError.write(Data("Bars: \(explanation)\n".utf8))
            return 1
        }
    }

    private static func requestReload() {
        WidgetCenter.shared.reloadTimelines(ofKind: SnapshotStore.widgetKind)
        // WidgetCenter sends the request asynchronously. The short-lived
        // publisher must keep its run loop alive long enough to send it.
        RunLoop.current.run(until: Date().addingTimeInterval(2))
    }

    private static func usage() -> Int32 {
        FileHandle.standardError.write(Data("Usage: Bars --check-storage | --publish-snapshot PATH [--no-reload] | --reload-widgets\n".utf8))
        return 2
    }
}
